[project]
name = "photography-studio-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff]
[tool.ruff.format]
quote-style = "single"